Repository AGH-Narzedzia-Informatyczne-2023-2024/Noname, pull requests merged in 2023-11, with the labels that each got.

#8 Poruszanie się po labiryncie
  nawigacja.py
Labels: enhancement, python

#7 Deklaracja planszy
  labirynt_anna.py
Labels: python

#10 Inicjalizacja bohatera
  Inicjalizacja_bohatera.py
Labels: good first issue, python, Pygame

#13 Dodaje plik z funkcjonalnością zapisu postępu gry
  postep.py
Labels: good first issue, python, Pygame

#11 Dodanie grafik i wstępna inicjalizacja ich
  python-grafiki/bohater.png
  python-grafiki/czas.png
  python-grafiki/grafiki.py
  python-grafiki/moneta.png
  python-grafiki/serce.png
Labels: good first issue, python, Pygame
